import "./globals.css";

export const metadata = {
  title: "Trello",
  description: "Generated by Jonathancsr",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
